name: gitme
on: [push]
jobs:
  gitme-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: timedatectl set-timezone America/New_York
      - run: npm install
      - run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: aboutDavid/aboutdavid
          BRANCH: main
          EMAIL: 62346025+aboutDavid@users.noreply.github.com
          NAME: aboutDavid
